# Generated by Django 5.0 on 2023-12-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_ID', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя из телеграмма')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('phone_num', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest1', models.TextField(verbose_name='Вопрос 1')),
                ('quest2', models.TextField(verbose_name='Вопрос 2')),
                ('quest3', models.TextField(verbose_name='Вопрос 3')),
                ('quest4', models.TextField(verbose_name='Вопрос 4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
    ]
