# Generated by Django 5.0 on 2023-12-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='tg_ID',
            field=models.CharField(max_length=100, verbose_name='ID пользователя из телеграмма'),
        ),
    ]
