# Generated by Django 5.0 on 2023-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_botuser_consent_mail_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillist',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Текст рассылки'),
        ),
    ]
