# Generated by Django 5.0 on 2023-12-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_maillist_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='quest1',
            field=models.CharField(max_length=100, verbose_name='Вопрос 1'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='quest2',
            field=models.CharField(max_length=100, verbose_name='Вопрос 2'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='quest3',
            field=models.CharField(max_length=100, verbose_name='Вопрос 3'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='quest4',
            field=models.CharField(max_length=100, verbose_name='Вопрос 4'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tg_ID',
            field=models.CharField(max_length=100, null=True, verbose_name='ID пользователя из телеграмма'),
        ),
    ]
